#version: '3'
services:
#chown -R 1100:1100 /graylog/graylog_journal
#-----
  mongodb:
    image: mongo:6.0
    networks:
      - graylog
    volumes:
      - /graylog/mongodb:/data/db
#------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - /graylog/elasticsearch:/var/lib/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - graylog
#----
  graylog:
    image: graylog/graylog:5.1
    volumes:
      - /graylog/graylog_journal:/usr/share/graylog/data/journal
#      - /graylog/plugins:/usr/share/graylog/plugin
    environment:
      - TZ=America/Sao_Paulo
      - GRAYLOG_ROOT_TIMEZONE=America/Sao_Paulo
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.205.4:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
#    command: ["wget","https://github.com/wizecore/graylog2-output-syslog/releases/download/v4.2.6/graylog-output-syslog-4.2.6.jar","-p", "/usr/share/graylog/plugin"]
    networks:
      - graylog
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
  plugins:
    driver: local
networks:
    graylog:
      driver: bridge
